//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the Clean Swift Xcode Templates,
//  see https://github.com/ViktorChernykh/clean-swift
//

import Foundation

enum ___VARIABLE_sceneName___ {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
